import type { Metadata } from "next";
import { Josefin_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";

const josefinSans = Josefin_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Offline Doc Collab",
  description: "Generated by create next app",
};

import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${josefinSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-[#FDF8F0] text-zinc-900 font-sans">
        <StoreProvider>{children}</StoreProvider>
        <Toaster theme="light" />
      </body>
    </html>
  );
}
